"""Tool for multimodal vision support using Ollama moondream model."""

import os
import threading
import time

from agent.cancellation import CancellationToken, OperationCancelled
from agent.ollama_runtime import OllamaService, OperationKind
from agent.runtime_config import get_runtime_config

SUPPORTED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}
MAX_IMAGE_BYTES = 25 * 1024 * 1024
_RUNTIME_CONFIG = get_runtime_config()
_VISION_SERVICE = OllamaService(_RUNTIME_CONFIG)

def describe_image(
    image_path: str,
    prompt: str = "Please provide a highly detailed description of this technical diagram, flowchart, or architecture slide.",
    cancellation_token: CancellationToken | None = None,
) -> str:
    """
    Send an image to the local moondream model and return its description.

    This function enables the agent to extract text descriptions and analyses
    from image files. It uses the Ollama python client to communicate with the
    'moondream' multimodal vision model.

    Args:
        image_path (str): The absolute or relative path to the image file.
        prompt (str): The text prompt guiding the model's description.

    Returns:
        str: The text content generated by the vision model describing the image,
             or an error string if the request fails.
    """
    if not os.path.exists(image_path):
        return f"Error: Image not found at {image_path}"
    if not os.path.isfile(image_path):
        return f"Error: Not a file: {image_path}"
    extension = os.path.splitext(image_path)[1].lower()
    if extension not in SUPPORTED_IMAGE_EXTENSIONS:
        return f"Error: Unsupported image type '{extension}'"
    if os.path.getsize(image_path) > MAX_IMAGE_BYTES:
        return "Error: Image exceeds the 25 MiB limit"
    prompt = str(prompt or "Describe this image.").strip()[:4000]
    
    try:
        thread_id = threading.get_ident()
        coordinator = _VISION_SERVICE.coordinator
        owner = (
            f"tool:{thread_id}"
            if coordinator.is_owned_by_current_context()
            else f"vision:{thread_id}:{time.monotonic_ns()}"
        )
        response = _VISION_SERVICE.chat(
            kind=OperationKind.VISION,
            owner=owner,
            model=_RUNTIME_CONFIG.vision_model,
            cancellation_token=cancellation_token,
            operation_timeout=_RUNTIME_CONFIG.vision_timeout_seconds,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                    "images": [image_path]
                }
            ],
            stream=False,
            think=False,
        )
        message = response.get("message") if isinstance(response, dict) else getattr(response, "message", None)
        content = message.get("content") if isinstance(message, dict) else getattr(message, "content", None)
        if not content:
            return "Error describing image: Ollama returned an empty response"
        return str(content)
    except OperationCancelled:
        raise
    except Exception as e:
        return f"Error describing image: {str(e)}"
